name: smart_utils_plus
description: A comprehensive Flutter utility package providing essential helper classes for date/time manipulation, string operations, device information, logging, and widget utilities.
version: 1.1.0
homepage: https://github.com/vkashegde/smart_utils_plus
repository: https://github.com/vkashegde/smart_utils_plus
issue_tracker: https://github.com/vkashegde/smart_utils_plus/issues

environment:
  sdk: ^3.6.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.19.0
  connectivity_plus: ^6.0.2
  device_info_plus: ^10.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0


flutter:
